import os
import requests
import json
import datetime
from dotenv import load_dotenv

load_dotenv()

def send_to_feishu(content: str, webhook_url: str):
    """
    发送飞书卡片消息
    """
    # 构造飞书卡片 JSON 结构
    # 我们使用 'interactive' 类型，它支持 Markdown 渲染
    payload = {
        "msg_type": "interactive",
        "card": {
            "header": {
                "title": {
                    "tag": "plain_text",
                    "content": f"🚨 SOTA Watch Daily ({datetime.date.today()})"
                },
                "template": "blue" # 标题颜色：blue, wathet, turquoise, green, yellow, orange, red, carmine, violet, purple, indigo, grey
            },
            "elements": [
                {
                    "tag": "markdown",
                    "content": content
                },
                {
                    "tag": "note",
                    "elements": [
                        {
                            "tag": "plain_text",
                            "content": f"Generated by AI Agent at {datetime.datetime.now().strftime('%H:%M')}"
                        }
                    ]
                }
            ]
        }
    }

    try:
        response = requests.post(
            webhook_url, 
            headers={"Content-Type": "application/json"}, 
            json=payload
        )
        
        # 检查飞书的返回结果
        result = response.json()
        if result.get("code") == 0:
            print("✅ [Feishu] Notification sent successfully!")
        else:
            print(f"❌ [Feishu] Failed. Error: {result}")
            
    except Exception as e:
        print(f"❌ [Feishu] Connection error: {e}")

def send_notification(content: str):
    """
    主通知入口
    """
    print("\n📨 [Notifier] Preparing notification...")
    
    # 1. 总是保存一份到本地 (备份)
    today = datetime.date.today().strftime("%Y-%m-%d")
    filename = f"sota_report_{today}.md"
    try:
        with open(filename, "a", encoding="utf-8") as f:
            f.write(f"\n\n🕒 Run Time: {datetime.datetime.now().strftime('%H:%M:%S')}\n")
            f.write(content)
        print(f"✅ Report saved to local file: {filename}")
    except Exception as e:
        print(f"❌ Failed to save local file: {e}")

    # 2. 检查是否有飞书配置
    feishu_url = os.getenv("FEISHU_WEBHOOK")
    
    if feishu_url:
        print("🚀 Sending to Feishu...")
        send_to_feishu(content, feishu_url)
    else:
        print("ℹ️  No FEISHU_WEBHOOK found in .env. Skipping cloud notification.")